site_name: QRL Wallet
nav:
  - Home: index.md
  - Overview: README.md
  - Whitepaper: WHITEPAPER.md
theme:
  name: mkdocs
markdown_extensions:
  - admonition
  - toc
  - tables
  - fenced_code
  - codehilite
