apiVersion: v1
kind: Service
metadata:
  name: qrl-wallet
  labels:
    app: qrl-wallet
spec:
  type: ClusterIP
  selector:
    app: qrl-wallet
  ports:
    - name: http
      port: 80
      targetPort: 5001
